#!/bin/bash
#PBS -j oe
#PBS -k doe

#PBS -N domain_flux_Hadriaca_Patera_cold_dry_fall
#PBS -m abe
#PBS -M palatyle@isu.edu
#PBS -l select=1:mem=30gb
#PBS -l walltime=00:30:00


#PBS -P edu_res

cd $PBS_O_WORKDIR
source /etc/profile.d/modules.sh

module load python/3.8-anaconda-2020.07
conda activate GCM2MATHAM

python MATHAM_domain_flux.py -i /scratch/palatyle/Hadriaca_Patera_cold_dry/MATHAM_fall_netCDF_MOV.nc -o /home/palatyle/LMD_gen/trunk/datagcm/Hadriaca_Patera_fall_cold_dry.txt

