%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/tylerpaladino/Documents/ISU/Thesis/Mars_atmos.xlsx
%    Worksheet: Sheet2
%
% Auto-generated by MATLAB on 16-Nov-2022 09:36:38

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "Sheet2";
opts.DataRange = "A3:B13";

% Specify column names and types
opts.VariableNames = ["grainsizephi", "wt"];
opts.VariableTypes = ["double", "double"];

% Import the data
tbl = readtable("/Users/tylerpaladino/Documents/ISU/Thesis/Mars_atmos.xlsx", opts, "UseExcel", false);

%% Convert to output type
grainsizephi = tbl.grainsizephi;
wt = tbl.wt;

%% Clear temporary variables
clear opts tbl


%% 
idx = [2, 5, 8, 9];

% semilogx(Diameter_mm,Masswt,'o-','linewidth',2.5, 'MarkerFaceColor', [0 0.4470 0.7410])
plot(grainsizephi,wt,'o-','linewidth',2.5, 'MarkerFaceColor', [0 0.4470 0.7410])

hold on
% semilogx(Diameter_mm(idx),Masswt(idx),'o','linewidth',2.5, 'MarkerFaceColor', [0.8500 0.3250 0.0980])
plot(grainsizephi(idx),wt(idx),'o','linewidth',2.5, 'MarkerFaceColor', [0.8500 0.3250 0.0980])

grid on 
grid minor
xlabel('Grain Diameter (\phi)')
ylabel('Wt %')
set(gca,'FontSize',18)
