#!/bin/bash
#PBS -j oe
#PBS -k doe

#PBS -N nc_volc_filt_Hadriaca_Patera_cold_dry_fall
#PBS -m abe
#PBS -M palatyle@isu.edu
#PBS -l select=1:mem=150gb
#PBS -l walltime=02:00:00

#PBS -P edu_res


cd $PBS_O_WORKDIR
source /etc/profile.d/modules.sh

module load python/3.8-anaconda-2020.07
conda activate GCM2MATHAM

python /home/palatyle/LMD_MATHAM_Utils/nc_volc_filt.py -i /scratch/palatyle/no_tharsis_Alba_Patera_cold_dry/diagfi.nc -o /scratch/palatyle/no_tharsis_Alba_Patera_cold_dry/Alba_Patera_diagfi_volc_filt.nc

